-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 08/12/2024 às 03:54
-- Versão do servidor: 10.4.28-MariaDB
-- Versão do PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `test`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `comentarios`
--

CREATE TABLE `comentarios` (
  `id` int(11) NOT NULL,
  `noticia_id` int(11) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `comentario` text NOT NULL,
  `data_comentario` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Estrutura para tabela `noticias`
--

CREATE TABLE `noticias` (
  `id` int(11) NOT NULL,
  `titulo` varchar(255) NOT NULL,
  `autor` varchar(255) NOT NULL,
  `categoria` varchar(100) NOT NULL,
  `conteudo` text NOT NULL,
  `url_imagem` varchar(255) DEFAULT NULL,
  `data_publicacao` timestamp NOT NULL DEFAULT current_timestamp(),
  `recomendada` tinyint(1) DEFAULT 0,
  `visualizacoes` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `noticias`
--

INSERT INTO `noticias` (`id`, `titulo`, `autor`, `categoria`, `conteudo`, `url_imagem`, `data_publicacao`, `recomendada`, `visualizacoes`) VALUES
(1, 'A Revolução dos Blockbusters: Como o Cinema Mudou na Última Década', 'Mariana Costa', 'cinema', 'Nos últimos dez anos, o cinema passou por uma transformação sem precedentes. A era dos blockbusters chegou a novos patamares, com produções cada vez mais grandiosas, orçamentos milionários e efeitos visuais que desafiam a realidade. O público foi presenteado com franquias icônicas como o Universo Cinematográfico Marvel, que redefiniu o conceito de sagas interconectadas e elevou as expectativas do público para os filmes de ação e aventura.\r\n\r\nPor outro lado, plataformas de streaming, como Netflix e Amazon Prime Video, também impactaram profundamente a indústria cinematográfica. Filmes que antes lutariam para ganhar espaço nas telonas agora encontram público fiel no conforto das casas. Com isso, diretores e roteiristas ganharam mais liberdade criativa, produzindo obras inovadoras como \"Roma\", de Alfonso Cuarón, e \"O Irlandês\", de Martin Scorsese.\r\n\r\nO futuro do cinema, no entanto, ainda levanta muitas questões. Enquanto o streaming cresce, as salas de cinema enfrentam desafios para se reinventar e continuar atraindo espectadores. A experiência única de assistir a um filme em uma sala escura, rodeado por outros fãs, será capaz de resistir à comodidade dos serviços digitais? A resposta parece estar na criatividade e no poder das histórias que só o cinema pode proporcionar.', 'https://campinas.com.br/wp-content/uploads/2023/09/pipoca-no-cinema-com-almofada-no-chao-scaled-e1695841582534.jpg', '2024-12-06 18:56:58', 1, 0),
(2, 'A Nova Era do Futebol Brasileiro: Jovens Talentos Conquistam o Mundo', 'Ricardo Oliveira', 'esportes', 'O futebol brasileiro vive uma nova era de protagonismo internacional, impulsionado pelo surgimento de jovens talentos que encantam dentro e fora do país. Jogadores como Endrick, Vitor Roque e João Gomes têm se destacado não apenas por suas habilidades técnicas, mas também por suas personalidades carismáticas que cativam torcedores de todas as idades.\r\n\r\nClubes brasileiros, como Palmeiras, Flamengo e Athletico Paranaense, têm desempenhado um papel fundamental nessa renovação. Investindo em categorias de base e em projetos de formação, eles não apenas criam oportunidades para jovens atletas como também garantem que o futebol brasileiro continue competitivo no cenário global. Esse trabalho reflete diretamente em transferências milionárias para gigantes europeus, consolidando o Brasil como um celeiro de craques.\r\n\r\nEnquanto isso, a seleção brasileira também colhe os frutos dessa nova geração. Após um ciclo de altos e baixos, a equipe começa a se renovar, mostrando um futebol mais dinâmico e envolvente. O sonho do hexacampeonato continua vivo, e com tantos talentos surgindo, o torcedor brasileiro pode ter esperança de que os próximos anos reservam conquistas históricas.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQALScpDxJV1cMN42FgNRA64r5duCos4PsmqA&s', '2024-12-06 19:00:51', 0, 0),
(3, 'Minimalismo: A Nova Tendência que Transforma Vidas', 'Camila Barreto', 'estilo_de_vida', 'O minimalismo tem ganhado espaço como um estilo de vida que preza pela simplicidade e pelo essencial. Em um mundo cada vez mais acelerado e repleto de excessos, muitas pessoas estão optando por reduzir seus pertences e focar naquilo que realmente importa, seja no ambiente doméstico, no guarda-roupa ou nas relações pessoais.\r\n\r\nO movimento vai além da estética. Adotar o minimalismo é um processo de autoconhecimento, onde aprendemos a desapegar de objetos que não agregam valor às nossas vidas e a priorizar experiências em vez de bens materiais. Essa mudança tem ajudado muitas pessoas a reduzir o estresse, aumentar a produtividade e encontrar mais felicidade em pequenas coisas.\r\n\r\nEspecialistas afirmam que o minimalismo também impacta positivamente o meio ambiente. Ao consumir menos, reduzimos a produção de resíduos e contribuímos para um mundo mais sustentável. Seja por motivos financeiros, emocionais ou ecológicos, o minimalismo veio para ficar, oferecendo uma nova perspectiva para quem busca equilíbrio e propósito no dia a dia.', 'https://images.ecycle.com.br/wp-content/uploads/2022/03/10180009/pexels-andrew-neel-7932264-scaled.jpg', '2024-12-06 19:01:54', 0, 0),
(4, 'Anitta Conquista o Mundo com Sua Nova Turnê Internacional', 'Mariana Costa', 'famosos', 'Anitta, um dos maiores nomes da música brasileira, está brilhando mais do que nunca em sua nova turnê internacional, que percorre América do Norte, Europa e Ásia. A cantora, que já conquistou diversas paradas musicais ao redor do mundo, leva uma mistura contagiante de funk, pop e reggaeton para fãs de diferentes culturas, consolidando sua posição como um ícone global.\r\n\r\nEm recente entrevista, Anitta compartilhou sua empolgação: “Levar a nossa cultura para o mundo é um dos maiores orgulhos da minha carreira. Cada show é uma troca incrível de energia com os fãs.” Suas apresentações têm sido marcadas por coreografias impressionantes, figurinos extravagantes e uma conexão única com o público.\r\n\r\nCom hits como “Envolver” e colaborações internacionais de sucesso, Anitta continua a expandir fronteiras e abrir portas para outros artistas brasileiros. Sua dedicação e autenticidade a tornam um exemplo de superação e inspiração, mostrando que é possível transformar sonhos em realidade com muito trabalho e paixão.', 'https://fly.metroimg.com/upload/q_85,w_700/https://uploads.metroimg.com/wp-content/uploads/2024/11/07185441/anitta-clipe-1.jpg', '2024-12-06 19:03:53', 0, 0),
(5, 'The Last of Us Part II: Um Marco na História dos Jogos Digitais', 'Rafael Monteiro', 'jogos_digitais', 'Desde o seu lançamento, The Last of Us Part II, da Naughty Dog, tem sido amplamente considerado um dos jogos mais impactantes e polêmicos da indústria de jogos digitais. Disponível para o PlayStation, o título conquistou prêmios como Jogo do Ano no The Game Awards, solidificando sua posição como um marco na narrativa interativa.\r\n\r\nA história continua os eventos do primeiro jogo, levando os jogadores a uma jornada emocional com Ellie, enquanto ela enfrenta perdas, conflitos internos e o desejo de vingança em um mundo pós-apocalíptico. O roteiro ousado e a profundidade dos personagens elevaram o patamar da narrativa em jogos, aproximando-os ainda mais do cinema em termos de storytelling.\r\n\r\nAlém disso, o jogo impressiona com seu realismo técnico. A Naughty Dog utilizou recursos avançados de captura de movimento e design sonoro, criando uma imersão sem precedentes. The Last of Us Part II também gerou discussões importantes sobre representatividade, com personagens LGBTQIA+ em destaque, mostrando como os jogos digitais podem ser uma plataforma poderosa para explorar questões sociais relevantes.', 'https://files.tecnoblog.net/wp-content/uploads/2021/05/the-last-of-us-2-ps5.jpeg', '2024-12-06 19:05:23', 0, 0),
(6, 'Amazônia em Foco: A Importância da Preservação do Maior Pulmão do Mundo', 'Ana Clara Medeiros', 'meio_ambiente', 'A Amazônia, conhecida como o maior pulmão do mundo, desempenha um papel vital na regulação do clima global e na biodiversidade. Com uma área de aproximadamente 5,5 milhões de quilômetros quadrados, esta floresta tropical abriga milhares de espécies únicas e comunidades indígenas que vivem em harmonia com a natureza há séculos. Contudo, a crescente devastação por desmatamento e queimadas ameaça seu futuro.\r\n\r\nNos últimos anos, a Amazônia enfrentou um aumento alarmante na taxa de desmatamento. Áreas enormes são destruídas para dar lugar à agricultura e pecuária, prejudicando não apenas o equilíbrio ecológico, mas também o abastecimento de água e a estabilidade climática global. Estima-se que a floresta esteja se aproximando de um ponto de não retorno, onde sua capacidade de regeneração será severamente comprometida.\r\n\r\nA preservação da Amazônia não é apenas uma responsabilidade brasileira, mas um esforço global. Projetos de reflorestamento, incentivos à agricultura sustentável e o fortalecimento da fiscalização são medidas essenciais para garantir que a Amazônia continue desempenhando seu papel crucial na saúde do planeta. A conscientização e o apoio de pessoas ao redor do mundo podem fazer a diferença, unindo esforços para proteger este tesouro natural para as futuras gerações.', 'https://blog.cresol.com.br/wp-content/uploads/2024/09/floresta-amazonica.png', '2024-12-06 19:06:30', 0, 0),
(7, 'A Revolução do Pop: O Fenômeno Billie Eilish', 'Rafael Santana', 'musica', 'Billie Eilish é um dos maiores nomes da música pop contemporânea, redefinindo os padrões do gênero com seu estilo único e autenticidade. Desde o lançamento de seu álbum de estreia, When We All Fall Asleep, Where Do We Go?, em 2019, a jovem cantora conquistou uma legião de fãs ao redor do mundo e um impressionante número de prêmios, incluindo diversos Grammys.\r\n\r\nCom apenas 17 anos na época de seu primeiro grande sucesso, Billie trouxe uma abordagem inovadora para o pop, misturando elementos eletrônicos, melodias suaves e letras introspectivas. Suas músicas, como \"bad guy\" e \"everything i wanted\", capturam as emoções de uma geração que busca autenticidade e conexão em um mundo muitas vezes superficial. Ao lado de seu irmão e produtor, Finneas, Billie conseguiu transformar sentimentos profundos em hits globais.\r\n\r\nAlém de sua música, Billie Eilish é reconhecida por seu impacto cultural. Ela é uma defensora da sustentabilidade, frequentemente abordando questões ambientais em entrevistas e eventos. Seu estilo de se vestir, muitas vezes ousado e fora dos padrões convencionais, também desafia normas de beleza tradicionais, promovendo a aceitação e individualidade. Com uma carreira ainda em ascensão, Billie Eilish continua a inspirar e moldar a indústria musical de maneira única e inovadora.', 'https://rollingstone.com.br/media/uploads/2024/06/billie-eilish-cantora-foto-sarah-morris-wireimage.jpg', '2024-12-06 19:07:19', 0, 0),
(8, 'Inteligência Artificial Generativa: A Revolução Tecnológica do Século', 'Marina Costa', 'tecnologia', 'Nos últimos anos, a inteligência artificial (IA) generativa tem transformado a forma como interagimos com a tecnologia e criamos conteúdos digitais. Ferramentas como o ChatGPT, DALL·E e MidJourney estão liderando uma revolução que permite criar textos, imagens, músicas e até vídeos de forma automatizada, economizando tempo e trazendo novas possibilidades criativas.\r\n\r\nO impacto dessa tecnologia já é evidente em diversas áreas. Na educação, professores e estudantes estão utilizando IA para elaborar materiais didáticos personalizados e simular experimentos científicos. No entretenimento, roteiros, ilustrações e até cenários completos podem ser desenvolvidos com o auxílio de IA, democratizando o acesso a recursos que antes eram restritos. Empresas também adotaram essas ferramentas para melhorar a produtividade, automatizando processos como redação de e-mails, atendimento ao cliente e planejamento de projetos.\r\n\r\nApesar do entusiasmo, a inteligência artificial generativa também levanta debates éticos. Como lidar com a autoria de conteúdos criados por máquinas? Como evitar o uso indevido, como a geração de fake news ou imagens manipuladas? Especialistas destacam a necessidade de regulamentação e conscientização sobre o uso responsável da tecnologia. Com um futuro ainda em construção, a IA generativa promete continuar surpreendendo, ao mesmo tempo em que desafia a sociedade a refletir sobre seu impacto e potencial.', 'https://blog.saninternet.com/wp-content/uploads/2024/04/inteligencia-artificial.png', '2024-12-06 19:08:18', 0, 0),
(10, 'O Retorno de James Bond', 'Mariana Costa', 'cinema', '007 – Sem Tempo Para Morrer\", lançado em 2021, marcou o retorno de Daniel Craig como o icônico agente secreto James Bond. O filme, que encerra a era de Craig no papel, apresenta uma história cheia de ação, suspense e emoção, com Bond enfrentando novos vilões e lidando com questões pessoais que aprofundam o personagem de forma única.\r\n\r\nDirigido por Cary Joji Fukunaga, o filme se destaca não apenas pela ação eletrizante, mas também pela qualidade de seu roteiro e performances. A atuação de Craig é aplaudida por mostrar um Bond mais vulnerável e introspectivo, algo que conquistou tanto fãs quanto críticos. O elenco também conta com grandes nomes como Rami Malek, na pele do vilão Safin, e Léa Seydoux, que retorna como Madeleine Swann.\r\n\r\nCom cenas de tirar o fôlego e uma trama cheia de reviravoltas, \"Sem Tempo Para Morrer\" é considerado um dos melhores filmes da franquia, encerrando a jornada de Craig de forma épica. O filme também traz reflexões sobre legado, perda e sacrifícios, elementos que fazem desse capítulo uma das despedidas mais emocionantes do cinema contemporâneo.', 'https://t.ctcdn.com.br/U9Lr_oIsL8S1otk0wqMxutCF9xw=/i490875.jpeg', '2024-12-07 02:21:58', 0, 0),
(11, 'A Consagração de Lionel Messi no Inter Miami', 'Lucas Almeida', 'esportes', 'Lionel Messi, um dos maiores jogadores de futebol de todos os tempos, deu um passo ousado em sua carreira ao se transferir para o Inter Miami em 2023. Após uma década de sucesso estrondoso no Barcelona e uma passagem vitoriosa pelo Paris Saint-Germain, Messi decidiu embarcar na aventura de jogar na Major League Soccer (MLS), buscando novos desafios e ajudando a elevar o futebol nos Estados Unidos.\r\n\r\nDesde sua chegada, Messi tem mostrado toda sua magia em campo, encantando os fãs com suas habilidades e gols espetaculares. Sua presença tem sido um divisor de águas para o Inter Miami, que, além de conquistar títulos, também viu um crescimento significativo na popularidade do esporte na região. O argentino trouxe consigo uma aura de grandes conquistas, motivando seus companheiros e fazendo a MLS ganhar ainda mais visibilidade global.\r\n\r\nAlém de suas atuações brilhantes, Messi tem sido um modelo de liderança e profissionalismo, tanto dentro quanto fora de campo. Sua transferência para os Estados Unidos representa uma nova fase no futebol, onde a experiência de lendas como ele pode inspirar a próxima geração e consolidar ainda mais a MLS como uma liga de referência no mundo do esporte.', 'https://cdn.folhape.com.br/img/pc/1100/1/dn_arquivo/2023/07/image-53.jpg', '2024-12-07 02:24:51', 0, 0),
(12, 'A Dieta Mediterrânea: Benefícios para a Saúde e Bem-Estar', 'Fernanda Lima', 'estilo_de_vida', 'A dieta mediterrânea tem ganhado destaque nos últimos anos por seus benefícios para a saúde e longevidade. Baseada nos hábitos alimentares tradicionais de países como Itália, Grécia e Espanha, ela é rica em frutas, vegetais, grãos integrais, peixes e azeite de oliva, promovendo uma alimentação equilibrada e nutritiva. Além disso, é associada à redução de doenças cardíacas, diabetes e até à melhora da saúde mental.\r\n\r\nEsse estilo de vida não se resume apenas à alimentação, mas também valoriza o prazer de comer com calma, desfrutando das refeições em boa companhia. A dieta mediterrânea incentiva o consumo moderado de vinho, especialmente tinto, e promove a prática de atividades físicas regulares, contribuindo para um envelhecimento saudável e ativo.\r\n\r\nAlém dos aspectos nutricionais, ela tem sido cada vez mais adotada como uma forma de bem-estar. Estudos indicam que seguir esses princípios pode resultar em uma vida mais equilibrada, com mais energia e disposição. A dieta mediterrânea, portanto, não é apenas uma tendência alimentar, mas uma verdadeira filosofia de vida, que cuida tanto do corpo quanto da mente.', 'https://image.tuasaude.com/media/article/vf/mk/dieta-mediterranea_18001_l.jpg', '2024-12-07 02:26:27', 0, 0),
(13, 'Beyoncé: A Reinvenção de uma Diva', 'Ricardo Souza', 'famosos', 'Beyoncé é, sem dúvida, uma das artistas mais influentes da música e cultura pop. Com uma carreira marcada por sucessos estrondosos e uma presença imponente no palco, ela conquistou fãs ao redor do mundo. Desde sua época no Destiny’s Child até sua carreira solo, Beyoncé sempre foi sinônimo de inovação, potência vocal e impacto social.\r\n\r\nAlém de sua música, Beyoncé também se destaca como empresária e ativista. Seus álbuns, como \"Lemonade\" e \"Renaissance\", vão além do entretenimento, abordando questões de identidade, empoderamento feminino e questões raciais. Sua capacidade de se reinventar, mantendo-se relevante e respeitada em um setor altamente competitivo, faz dela uma verdadeira lenda.\r\n\r\nBeyoncé não é apenas uma artista, mas um ícone cultural, que influencia não só a música, mas também a moda, o cinema e o comportamento social. Sua dedicação ao trabalho e seu compromisso com suas raízes e com causas sociais fazem dela uma das personalidades mais admiradas e admiráveis do século XXI.', 'https://istoe.com.br/wp-content/uploads/2024/09/beyonce.jpg?x60234', '2024-12-07 02:27:44', 0, 0),
(14, 'O Impacto de \"The Legend of Zelda: Tears of the Kingdom\"', 'Eduardo Martins', 'jogos_digitais', 'O lançamento de \"The Legend of Zelda: Tears of the Kingdom\" em 2023 causou um verdadeiro alvoroço no mundo dos games. Como sequência de \"Breath of the Wild\", o jogo trouxe novas mecânicas, um mapa expansivo e uma narrativa envolvente que cativou tanto fãs antigos quanto novos. A Nintendo conseguiu, mais uma vez, elevar a franquia a um novo patamar de inovação e imersão.\r\n\r\nO jogo se destaca por sua jogabilidade aberta, onde os jogadores têm a liberdade de explorar vastos cenários e resolver quebra-cabeças de forma criativa. A introdução de novos poderes e habilidades de Link, além da evolução no enredo, mantém a essência da série, mas também traz uma sensação de novidade que mantém os jogadores vidrados. A interação entre elementos do ambiente e o uso de física tornam a experiência única e cheia de surpresas.\r\n\r\nCom uma trama que explora temas de sacrifício, destino e a luta entre o bem e o mal, \"Tears of the Kingdom\" também é elogiado pela sua profundidade emocional. Seu sucesso foi imediato, e o jogo se consolidou como um dos maiores sucessos da Nintendo, reafirmando o legado de Zelda como uma das franquias mais amadas e respeitadas da história dos jogos digitais.', 'https://gizmodo.uol.com.br/wp-content/blogs.dir/8/files/2024/08/Tears-of-the-Kingdom-wallpaper-1170x720-1.jpg', '2024-12-07 02:32:15', 0, 0),
(15, 'O Desafio das Florestas: Desmatamento e Suas Consequências', 'Paula Costa', 'meio_ambiente', 'O desmatamento continua sendo um dos maiores desafios ambientais enfrentados pelo planeta. As florestas, responsáveis por regular o clima, preservar a biodiversidade e armazenar carbono, estão sendo devastadas a um ritmo alarmante, especialmente na Amazônia. Isso não só ameaça a fauna e flora local, mas também contribui significativamente para as mudanças climáticas globais, uma vez que as árvores desempenham um papel vital na absorção do dióxido de carbono.\r\n\r\nAlém dos danos ecológicos, o desmatamento afeta diretamente as comunidades indígenas e tradicionais que dependem das florestas para sua sobrevivência. A perda desses territórios também coloca em risco seus modos de vida e a preservação de culturas milenares. As atividades ilegais, como a exploração madeireira, a grilagem de terras e a expansão da agricultura, são algumas das principais causas desse problema.\r\n\r\nPara enfrentar essa crise, é fundamental adotar políticas públicas mais eficazes, promover a conscientização sobre a importância das florestas e buscar alternativas sustentáveis para o uso da terra. A recuperação das áreas desmatadas e o incentivo à preservação são essenciais para garantir um futuro mais equilibrado e saudável para as próximas gerações.', 'https://images01.brasildefato.com.br/91c399d86532f05061692cda2c8cbda4.jpeg', '2024-12-07 02:33:27', 0, 0),
(16, 'O Renascimento do Rock: A Nova Geração de Bandas', 'Carlos Almeida', 'musica', 'O rock, gênero que já foi sinônimo de revolução musical, está passando por um renascimento com a chegada de novas bandas que mesclam o estilo clássico com sonoridades contemporâneas. Grupos como Greta Van Fleet, Wolf Alice e Royal Blood estão conquistando fãs ao redor do mundo, trazendo frescor ao rock e provando que, apesar das mudanças na indústria musical, o gênero ainda tem muito a oferecer.\r\n\r\nEssas bandas, que se inspiram no legado de gigantes como Led Zeppelin e Nirvana, incorporam influências do indie, do grunge e até do eletrônico, criando um som híbrido e inovador. Com letras profundas e riffs poderosos, o rock moderno se reinventa, atraindo tanto os fãs antigos quanto os mais jovens, que estão redescobrindo a força e a autenticidade da guitarra.\r\n\r\nO retorno do rock também está se refletindo nos grandes palcos e festivais de música, com novas gerações acompanhando shows épicos e se conectando com a energia vibrante desse estilo. O rock nunca morreu, ele apenas se transformou, e a nova onda de bandas está aqui para garantir que o legado desse gênero continue a ser uma das maiores expressões musicais do nosso tempo.', 'https://recreio.com.br/media/uploads/aleatorio/rock_capa.jpg', '2024-12-07 02:34:34', 0, 0),
(17, '5G: A Revolução na Conexão de Internet', 'Lucas Martins', 'tecnologia', 'O 5G chegou para transformar a maneira como nos conectamos à internet. Com uma velocidade muito mais rápida que o 4G, a nova geração de redes móveis promete não só melhorar a experiência de navegação, mas também impulsionar inovações em áreas como inteligência artificial, internet das coisas (IoT) e realidade aumentada. A latência extremamente baixa do 5G torna possível realizar tarefas em tempo real, impactando desde a forma como assistimos a vídeos até como interagimos com dispositivos inteligentes.\r\n\r\nAlém das melhorias para usuários comuns, o 5G abre portas para o avanço de tecnologias em setores como saúde, automação e transporte. Em hospitais, por exemplo, a conexão de alta velocidade pode permitir cirurgias remotas com precisão milimétrica. No setor automotivo, o 5G é fundamental para o desenvolvimento de carros autônomos, garantindo que os veículos se comuniquem entre si e com a infraestrutura urbana em tempo real, aumentando a segurança nas estradas.\r\n\r\nApesar de todas as promessas, a implementação do 5G ainda enfrenta desafios, como a necessidade de infraestrutura e os custos envolvidos. Além disso, questões de segurança e privacidade precisam ser cuidadosamente avaliadas, já que a maior conectividade também pode abrir brechas para ataques cibernéticos. A revolução do 5G está apenas começando, e, com ela, novas possibilidades de transformar o nosso modo de viver e trabalhar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREQKCAstqFv8hKT2T9_1-GnrcjD2J25UJMeQ&s', '2024-12-07 02:37:28', 0, 0);

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `comentarios`
--
ALTER TABLE `comentarios`
  ADD PRIMARY KEY (`id`),
  ADD KEY `noticia_id` (`noticia_id`);

--
-- Índices de tabela `noticias`
--
ALTER TABLE `noticias`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `comentarios`
--
ALTER TABLE `comentarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT de tabela `noticias`
--
ALTER TABLE `noticias`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- Restrições para tabelas despejadas
--

--
-- Restrições para tabelas `comentarios`
--
ALTER TABLE `comentarios`
  ADD CONSTRAINT `comentarios_ibfk_1` FOREIGN KEY (`noticia_id`) REFERENCES `noticias` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
